kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "rhel7-devimage-build"
spec:
  source:
    git:
      uri: https://github.com/ryan-highley/ocp-advdev-homework.git
    contextDir: "rhel7-devimage"
  strategy:
    dockerStrategy:
      dockerfilePath: "./Dockerfile"
  output:
    to:
      kind: "ImageStreamTag"
      name: "rhel7-devimage:latest"