
- name: deploy gogs
  include_tasks: gogs.yml
  when: include_gogs == true

- name: deploy nexus
  include_tasks: nexus.yml
  when: include_nexus == true

- name: deploy sonarqube
  include_tasks: sonarqube.yml
  when: include_sonarqube == true

- name: deploy jenkins
  include_tasks: jenkins.yml
  when: include_jenkins == true
