---
- name: build-tools-project playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - "vars/vars.yml"
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: provision-build-tools-project
    playbook_debug: false